### ISSUE TITLE
v2.3b not working

### ISSUE THREAD

**Issue by cwken10** [OfficialAName/AntiBotUltra-1.8-1.9#4]
not working in spigot 1.9.4
problems:
- when bot attack, chat keep spam player left the game (all is same name)
- antibot totally no working
- even i do "/sensibility 2" wont pop out any message

**Comment by OfficialAName** [comment]
there will be released 2.4b that will fix the commands. Could you have more details about antibot by "totally not working" and "when bot attack, chat keep spam player left the game (all is same name)"?

**Comment by cwken10** [comment]
This is my player recorded video, also a only one video, but need join the
fb group to see

2016年9月16日 下午8:07，"David" <notifications@github.com>写道：

**Comment by cwken10** [comment]
https://www.facebook.com/groups/huskycraft/permalink/516265261906233/

2016年9月21日 下午12:56，"Chan Ken" <cwken10@gmail.com>写道：

**Comment by OfficialAName** [comment]
Can you give me the video link? i'm not going to join nobody's group.

**Comment by cwken10** [comment]
i downloaded the video

**Comment by OfficialAName** [comment]
...link?

**Comment by cwken10** [comment]
it just a 2mb video..

**Comment by cwken10** [comment]
i uploaded to my youtube
https://youtu.be/OVaFbWWyeW0

**Comment by OfficialAName** [comment]
That's not a problem or spam. This happens because of essentials join/leave message! It has nothing to do with AntiBot-Ultra!

**Comment by cwken10** [comment]
When bot attack without AntiBotUltra, it won't spam duplicates leave
message, the spam is not too fast, i can see it

Same attack power when installed AntiBotUltra, the plugin causing server
send message unstable

2016年9月23日 下午9:45，"David" <notifications@github.com>写道：

**Comment by OfficialAName** [comment]
Closed as i gave'd answer.
